openapi: 3.0.0
info:
  title: 'Endpoints (3): Organisation settings'
  version: '1.0'
  description: |-
    The organisation settings endpoints enable you to manage your Thrust Carbon's organisational settings.

    #### Getting Started
    **If it is your first time here, we suggest visiting the [Getting Started guide](../docs/Getting-started.md).**
  contact:
    url: 'https://www.thrustcarbon.com'
    name: Kit Brennan
    email: kit@thrustcarbon.com
servers:
  - url: 'https://app.thrustcarbon.com/'
    description: Production
paths:
  api/1/setting/organisation/sub-organisations:
    parameters: []
    get:
      summary: 'Sub organisation: list'
      tags:
        - Sub organisations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../models/common-models/response-paginated.v1.json
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: ../models/common-models/organisation.v1.yaml
                    type: object
      operationId: get-organisationId-organisations
      description: |-
        > ### This endpoint is only accessible by partner accounts
        > Please contact your account manager for access.

        This endpoint will list all the sub-organisation's belonging to this organisation. 
    post:
      summary: 'Sub organisation: add'
      operationId: post-organisationId-organisations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/common-models/organisation.v1.yaml
      description: |-
        > ### This endpoint is only accessible by partner accounts
        > Please contact your account manager for access.

        This endpoint will create a new sub-organisation under this organisation.

        **Usage of this endpoint will cost you money.** Each new partner account is billed as a new Thrust Carbon license. Please contact your account manager for pricing.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                is_partner:
                  type: boolean
                  description: 'If this organisation is a partner account, it will be able to have further sub-organisations below it. *Note: you will be billed for these sub-organisations*.'
                organisation_id:
                  type:
                    - string
                    - 'null'
                  description: 'Organisation that the sub-organisation will be placed under. If not supplied, it will default to your root organisation.'
              required:
                - name
      tags:
        - Sub organisations
    delete:
      summary: 'Sub organisation: delete'
      operationId: delete-organisationId-organisations
      responses:
        '204':
          description: No Content
      description: |-
        > ### This endpoint is only accessible by partner accounts
        > Please contact your account manager for access.

        This endpoint will delete the organisation, using the organisation ID in the path.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                organisation_id:
                  type: string
                  description: ID of the sub-organisation to delete.
        description: ''
      tags:
        - Sub organisations
  /api/1/setting/organisation/departments:
    get:
      summary: 'Departments: List'
      tags:
        - Departments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../models/common-models/response-paginated.v1.json
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: ../models/common-models/department.v1.yaml
                    required:
                      - data
      operationId: get-api-1-setting-organisation-departments
      description: |-
        This list endpoint will provide a paginated list of all departments in your organisation.

        ---
        #### Description of department endpoints

        **Department endpoints let you set additional details for each department key**. These additional details are use in other Thrust Carbon products, such as correct department names on Thrust Calculator reports or in the Thrust Engage dashboard. 

        For example, a department with key '123' may have the name 'US HR' attached, and a description of 'Human Resources department for United States'. Since the department id of '123' is not understandable to most users, the name can be used instead.

        --- 
        #### Online interface

        You may create/read/update/delete departments manually via your account settings at https://app.thrustcarbon.com
    post:
      summary: 'Departments: Add'
      operationId: post-api-1-setting-organisation-departments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/common-models/department.v1.yaml
              examples:
                Parent department:
                  value:
                    key: '123'
                    parent_key: null
                    name: US HR
                    description: Human Resources for the United States
                Child department:
                  value:
                    key: '456'
                    parent_key: '123'
                    name: US East Coast HR
                    description: Human Resources for the Eastern seaboard of the United States
      description: |-
        This add endpoint will create or overwrite a department.

        ---
        #### Description of department endpoints

        **Department endpoints let you set additional details for each department key**. These additional details are use in other Thrust Carbon products, such as correct department names on Thrust Calculator reports or in the Thrust Engage dashboard. 

        For example, a department with key '123' may have the name 'US HR' attached, and a description of 'Human Resources department for United States'. Since the department id of '123' is not understandable to most users, the name can be used instead.

        --- 
        #### Online interface

        You may create/read/update/delete departments manually via your account settings at https://app.thrustcarbon.com
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
                parent_key:
                  type: string
                  description: The department's parent key must already be saved.
                title:
                  type: string
                  maxLength: 250
                description:
                  type: string
                  maxLength: 2000
              required:
                - key
                - title
            examples:
              Parent department:
                value:
                  key: '123'
                  name: US HR
                  description: Human Resources for the United States
              Child department:
                value:
                  key: '456'
                  parent_key: '123'
                  name: US East Coast HR
                  description: Human Resources for the Eastern seaboard of the United States
      tags:
        - Departments
    delete:
      summary: 'Departments: Remove'
      operationId: delete-api-1-setting-organisation-departments
      responses:
        '204':
          description: No Content
      description: |-
        This delete endpoint will remove a department definition. If the department has children, it will also remove those child definitions.

        ---
        #### Description of department endpoints

        **Department endpoints let you set additional details for each department key**. These additional details are use in other Thrust Carbon products, such as correct department names on Thrust Calculator reports or in the Thrust Engage dashboard. 

        For example, a department with key '123' may have the name 'US HR' attached, and a description of 'Human Resources department for United States'. Since the department id of '123' is not understandable to most users, the name can be used instead.

        --- 
        #### Online interface

        You may create/read/update/delete departments manually via your account settings at https://app.thrustcarbon.com
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                key:
                  type: string
              required:
                - key
        description: ''
      tags:
        - Departments
components:
  schemas: {}
  securitySchemes:
    API Key:
      type: http
      scheme: bearer
      description: 'Your API Key must be provided as a bearer token. To do this, create an ''Authorization'' header with a value of ''Bearer {your-api-key}'' (e.g. "Authorization: Bearer xcvboy23idvh").'
security:
  - API Key: []
tags:
  - name: Sub organisations
  - name: Departments
