openapi: 3.0.0
info:
  title: 'Endpoints (4): Thrust Engage'
  version: '1.0'
  description: |-
    > ### ALPHA ENDPOINT
    > Please contact your account manager for access. 
    <!-- theme: warning -->
    > ### ACTIVE DEVELOPMENT
    > We are proud to be actively developing the Thrust Engagement feature. These endpoints are likely to change, and/or may be discontinued. We advise against using these endpoints for any production workloads.

    The Thrust Engage endpoints enable you to build tools that bring about behaviour change to lower emissions. If you are looking for tools that calculate emissions, or enable you to offset emissions, you should look at other Thrust Carbon endpoints.
  contact: {}
servers:
  - url: 'https://app.thrustcarbon.com'
paths:
  /api/1/engage/suggestions/journey:
    post:
      summary: 'Suggestions: Journey'
      tags:
        - Suggestions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  emission_summary:
                    $ref: ../models/common-models/emission.v1.json
                  alternative_suggestions:
                    type: array
                    items:
                      $ref: ../models/common-models/alternative-suggestion.v1.yaml
                  carbon_budget:
                    description: 'Carbon tax is unavailable, please ignore at this time or speak to your account manager.'
                    type: object
                    properties:
                      budget_available:
                        type: number
                        description: Indicates the carbon budget available to the user before they create their emission.
                      budget_remaining:
                        type: number
                        description: 'Indicates the carbon budget available to their user after they make the emission. Note: budget_remaining is simply the budget_available, minus the tonnes_of_emissions in the emission_summary section.'
                      links:
                        type: array
                        items:
                          type: object
                          properties:
                            title:
                              type: string
                            uri:
                              type: string
                              format: uri
                            order:
                              type: number
                              description: Links are ranked by order of importance.
                          required:
                            - title
                            - uri
                            - order
                    required:
                      - budget_available
                      - budget_remaining
                      - links
                required:
                  - emission_summary
              examples:
                example-1:
                  value:
                    emission_summary:
                      tonnes_of_emissions: 14.28420582
                      equivalencies:
                        - type: string
                          values:
                            - string
                      invalid_segments:
                        - '3':
                            - The class of travel was invalid.
                          '5':
                            - 'The locations[1] was invalid.'
                    alternative_suggestions:
                      - type: rail
                        order: 1
                        heading: Have you considered high speed rail?
                        body: 'You can take the same journey with less stress, and far less polution, using a high speed train.'
                        links:
                          - uri: 'https://example.com'
                            order: 1
                            title: Explore high speed rail options
                    carbon_budget:
                      budget_available: 38
                      budget_remaining: 23.71579418
                      links:
                        - title: View your carbon budget
                          uri: 'https://example.com'
                          order: 1
      operationId: get-suggestions-journey
      description: |-
        > ### ALPHA ENDPOINT
        > Please contact your account manager for access. 

        This endpoint will fetch sustainability suggestions for a given journey. Depending on the segments supplied, there will be one or more suggestion:
        * _Carbon budget suggestions_: provides information about the usage of a user's carbon budget, and the remaining carbon budget.
        * _Alternative suggestions_: which will tell you lower carbon alternativest to reach the same destination.
        * _Summary of emissions_: which will tell you the amount emitted and give 'equivalencies' to the CO2 impact.

        A _Summary of emissions_ will be provided with every request, however other suggestion types may not be. You should **use descending priority** if you receive two or more suggestion types (e.g. display carbon tax, rather than summary of emissions).

        ### Testing

        White the _Summary of emissions_ is always provided, the _Alternate suggestions_ depends on the route searched, and the _Summary of emissions_ depends on the end-client. For this reason, you can force these suggestions by supplying the following input:

        * To test _Alternative Suggestions_ please pass through a flight segment, with locations `LHR` and `CDG`. This will return a high speed rail suggestion
        * To test _Carbon budget suggestions_ please pass through an employee_id and/or department_id of `THRUST_CARBON_TEST`.

        ### Notes

        * Please ensure you only provide a maximum of **2 locations for each segment**. If you have a return journey, please create two segments, one for the outbound leg, and one for the return leg.
      parameters:
        - in: unknown
        - schema:
            type: string
            example: en-US
            default: en-US
          in: header
          name: Accept-Language
          description: 'Enables us to return responses in the client''s language and localisation. This header is very important to providing a great end-user experience. More info at: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language'
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                employee_id:
                  description: 'Not required, but when provided this is useful for calculating an employee''s carbon budget.'
                  type: string
                department_id:
                  type: string
                  description: 'Not required, but if provided it. may be used to calculate a department''s carbon budget.'
                segments:
                  type: array
                  items:
                    allOf:
                      - $ref: ../models/segment-requests/segment-request.v1.yaml
            examples: {}
    parameters: []
components:
  schemas: {}
  securitySchemes:
    API Key:
      type: http
      scheme: bearer
      description: 'Your API key can be found in your account. To learn how to use your token, please see '
security:
  - API Key: []
tags:
  - name: Suggestions
